message(${CMAKE_CURRENT_LIST_DIR}/AudioProbe.cpp)
add_executable(AudioProbe  ${CMAKE_CURRENT_LIST_DIR}/AudioProbe.cpp ${SRC})
target_include_directories(AudioProbe PRIVATE ${INCL})
target_compile_options(AudioProbe PRIVATE ${COMPILE_OPTION} )
if(UNIX AND NOT APPLE)	
	target_link_libraries(AudioProbe m ${LINKLIBS})
else()
	target_link_libraries(AudioProbe ${LINKLIBS})
endif()
set_target_properties(AudioProbe PROPERTIES  CXX_STANDARD 14 )